import { ModalProvider } from "@/context/ModalContext";
import "./globals.css";
import WrapperLayout from "@/components/layout/WrapperLayout";

export const metadata = {
  title: "최애의 포토",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko" className="font-noto">
      <body>
        <ModalProvider>
          <WrapperLayout>{children}</WrapperLayout>
        </ModalProvider>
      </body>
    </html>
  );
}
