import {ModalProvider} from '@/components/modal/ModalContext';
import ModalRenderer from '@/components/modal/ModalRenderer';
import ReactQueryProvider from '../providers/ReactQueryProvider';
import './globals.css';
import WrapperLayout from '@/components/layout/WrapperLayout';

export const metadata = {
  title: '최애의 포토',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="ko" className="font-noto">
      <body>
        <ReactQueryProvider>
          <ModalProvider>
            <WrapperLayout>{children}</WrapperLayout>
            <ModalRenderer />
          </ModalProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
