import { ModalProvider } from "@/context/ModalContext";
import "./globals.css";
import WrapperLayout from "@/components/layout/WrapperLayout";
import AuthProvider from "@/providers/AuthProvider";
import Modal from "@/components/common/Modal";
import RouteGuard from "@/providers/RouteGuard";

export const metadata = {
  title: '최애의 포토',
  description: 'Generated by create next app',
};

export default function RootLayout({children}) {
  return (
    <html lang="ko" className="font-noto">
      <body>
        <AuthProvider>
          <RouteGuard>
            <ReactQueryProvider>
              <ModalProvider>
                <WrapperLayout>{children}</WrapperLayout>
                <Modal />
              </ModalProvider>
            </ReactQueryProvider>
          </RouteGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
